#!/usr/bin/env python3
"""Generate and check the game/payload boundary declared in abi.py.

  gen_abi.py entries   write src/gdx_entries.h (before compiling main.c)
  gen_abi.py release   record the current ENTRIES/PINNED in abi_released.json

conv_asm.py calls check() and the emit_* functions after linking.
"""
import json
import os
import sys

import abi

HERE = os.path.dirname(os.path.abspath(__file__))
RELEASED = os.path.join(HERE, "abi_released.json")
HOST_HEADER = os.path.join(HERE, "..", "core", "gdxsv", "gdxsv_patch_abi.h")


def entry_symbol(name):
    return "gdx_entry_" + name


def target_symbol(target):
    if target.startswith("entry:"):
        return entry_symbol(target[len("entry:"):])
    return target


def fail(message):
    sys.exit(f"gen_abi: {message}")


def check_declarations():
    names = {e.name for e in abi.ENTRIES}
    if len(names) != len(abi.ENTRIES):
        fail("duplicate entry name")
    slots = sorted(abi.ENTRIES, key=lambda e: e.addr)
    for a, b in zip(slots, slots[1:]):
        if a.addr + abi.ENTRY_SIZE > b.addr:
            fail(f"entries {a.name} and {b.name} overlap")
    for e in slots:
        if not (abi.ENTRY_BASE <= e.addr and e.addr + abi.ENTRY_SIZE <= abi.ENTRY_LIMIT) or e.addr % 4:
            fail(f"entry {e.name} at {e.addr:#010x} is outside the entry area or misaligned")
    for h in abi.HOOKS:
        if h.target.startswith("entry:"):
            if h.target[len("entry:"):] not in names:
                fail(f"hook at {h.addr:#010x} targets unknown {h.target}")
        elif h.target not in abi.PINNED:
            fail(f"hook at {h.addr:#010x} targets {h.target}, which is neither an entry nor pinned")

    if os.path.exists(RELEASED):
        released = json.load(open(RELEASED))
        entries = {e.name: e for e in abi.ENTRIES}
        for name, (addr, reg) in released["entries"].items():
            e = entries.get(name)
            if e is None or e.addr != int(addr, 16) or e.reg != reg:
                fail(f"released entry {name} was removed or changed")
        for sym, addr in released["pinned"].items():
            if abi.PINNED.get(sym) != int(addr, 16):
                fail(f"released pinned symbol {sym} was removed or moved")


def check(symbols):
    """symbols: name -> address of the linked payload."""
    check_declarations()
    for e in abi.ENTRIES:
        if e.target not in symbols:
            fail(f"entry {e.name} targets missing symbol {e.target}")
        if symbols.get(entry_symbol(e.name)) != e.addr:
            fail(f"{entry_symbol(e.name)} is not at {e.addr:#010x}")
    for sym, addr in abi.PINNED.items():
        if symbols.get(sym) != addr:
            got = symbols.get(sym)
            fail(f"{sym} is at {got:#010x}, pinned at {addr:#010x}" if got is not None else f"{sym} is missing")


def write_entries(path):
    check_declarations()
    lines = ["// Generated by gdxsv_patch/gen_abi.py from abi.py. Do not edit.",
             "// Fixed jump slots: the only payload code addresses handed to the game.",
             "asm(",
             '    ".pushsection gdx.func.entry,\\"ax\\",@progbits\\n"']
    for e in sorted(abi.ENTRIES, key=lambda e: e.addr):
        sym = entry_symbol(e.name)
        lines += [f'    ".org {e.addr - abi.ENTRY_BASE:#x}\\n"',
                  f'    ".global {sym}\\n"',
                  f'    "{sym}:\\n"',
                  f'    "\\tmov.l\\t1f,{e.reg}\\n"',
                  f'    "\\tjmp\\t@{e.reg}\\n"',
                  f'    "\\t nop\\n"',
                  f'    "\\t.balign 4\\n"',
                  f'    "1:\\t.long\\t{e.target}\\n"']
    lines += ['    ".popsection\\n"', ");", ""]
    lines += [f"void {entry_symbol(e.name)}(void);" for e in abi.ENTRIES]
    open(path, "w", newline="\n").write("\n".join(lines) + "\n")


def cxx_target(target):
    return f'symbols_["{target_symbol(target)}"]'


def emit_payload_hooks(f):
    """Install code run with the payload, before the SH4 resumes."""
    for feature in abi.PAYLOAD_FEATURES:
        for disk in (1, 2):
            hooks = [h for h in abi.HOOKS if h.feature == feature and h.disk == disk]
            if not hooks:
                continue
            if all(h.stock is None for h in hooks):
                for h in hooks:
                    f.write(f"if (disk_ == {disk}) gdxsv_WriteMem32(0x{h.addr:08x}, {cxx_target(h.target)});\n")
                continue
            # All or nothing, only on the known ROM layout.
            checks = []
            for h in hooks:
                values = [f"0x{h.stock:08x}", cxx_target(h.target)] + [f"0x{v:08x}" for v in h.legacy]
                checks.append("(" + " || ".join(f"gdxsv_ReadMem32(0x{h.addr:08x}) == {v}" for v in values) + ")")
            f.write(f"if (disk_ == {disk}) {{\n")
            f.write("    if (" + "\n        && ".join(checks) + ") {\n")
            for h in hooks:
                if h.repair_only:
                    legacy = " || ".join(f"gdxsv_ReadMem32(0x{h.addr:08x}) == 0x{v:08x}" for v in h.legacy)
                    f.write(f"        if ({legacy})\n    ")
                f.write(f"        gdxsv_WriteMem32(0x{h.addr:08x}, {cxx_target(h.target)});\n")
            f.write("    } else {\n")
            f.write(f'        WARN_LOG(COMMON, "{feature} hooks: unexpected guest pointers; not installed");\n')
            f.write("    }\n}\n")
    # Host-installed features: relocate hooks a released payload left behind.
    for h in abi.HOOKS:
        if h.feature not in abi.PAYLOAD_FEATURES and h.legacy:
            legacy = " || ".join(f"gdxsv_ReadMem32(0x{h.addr:08x}) == 0x{v:08x}" for v in h.legacy)
            f.write(f"if (disk_ == {h.disk} && ({legacy}))\n")
            f.write(f"    gdxsv_WriteMem32(0x{h.addr:08x}, {cxx_target(h.target)});\n")


def camel(name):
    return "".join(part.capitalize() for part in name.split("_"))


def write_host_header(path):
    host = sorted({h.feature for h in abi.HOOKS} - set(abi.PAYLOAD_FEATURES))
    kinds = list(dict.fromkeys(v.kind for v in abi.VALUES))
    out = ["// Generated by gdxsv_patch/gen_abi.py from abi.py. Do not edit.",
           "// Game sites of the features the host installs.",
           "#pragma once",
           "#include \"types.h\"",
           "",
           "namespace gdxsv_abi {",
           "enum class Kind { " + ", ".join(camel(k) for k in kinds) + " };",
           "struct Hook { int disk; u32 addr; u32 stock; const char *target; };",
           "struct Code { int disk; u32 addr; u16 stock; u16 patched; };",
           "struct Value { int disk; Kind kind; u32 addr; u32 stock; };",
           ""]
    for feature in host:
        out.append(f"constexpr Hook {feature}_hooks[] = {{")
        out += [f'	{{{h.disk}, 0x{h.addr:08x}, 0x{h.stock:08x}, "{target_symbol(h.target)}"}},'
                for h in abi.HOOKS if h.feature == feature]
        out.append("};")
        out.append(f"constexpr Code {feature}_code[] = {{")
        for c in abi.CODE:
            if c.feature == feature:
                out += [f"	{{{c.disk}, 0x{c.addr + 2 * i:08x}, 0x{stock:04x}, 0x{patched:04x}}},"
                        for i, (stock, patched) in enumerate(zip(c.stock, c.patched))]
        out.append("};")
        out.append(f"constexpr Value {feature}_values[] = {{")
        out += [f"	{{{v.disk}, Kind::{camel(v.kind)}, 0x{v.addr:08x}, 0x{v.stock:08x}}},"
                for v in abi.VALUES if v.feature == feature]
        out.append("};")
    out += ["} // namespace gdxsv_abi", ""]
    open(path, "w", newline="\n").write("\n".join(out))


def write_released():
    check_declarations()
    data = {"entries": {e.name: [f"0x{e.addr:08x}", e.reg] for e in abi.ENTRIES},
            "pinned": {sym: f"0x{addr:08x}" for sym, addr in abi.PINNED.items()}}
    json.dump(data, open(RELEASED, "w", newline="\n"), indent=2)
    print(f"recorded {len(abi.ENTRIES)} entries and {len(abi.PINNED)} pinned symbols")


if __name__ == "__main__":
    if sys.argv[1:] == ["entries"]:
        write_entries(os.path.join(HERE, "src", "gdx_entries.h"))
    elif sys.argv[1:] == ["release"]:
        write_released()
    else:
        sys.exit(__doc__)
